/* eslint-disable react/no-danger */
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import { FC, PropsWithChildren } from 'react';
import { Analytics } from '@vercel/analytics/react';
import { LoadingIndicator } from 'src/shared/Loading';
import { ApolloClientProvider } from 'src/providers/ApolloProvider';
// import { CommandBar } from 'src/shared/Kbar';
import ThemeProvider from 'src/providers/ThemeProvider';
import '../styles/syntax-nord.css';
import '../styles/styles.css';
import '../styles/shadow-icon.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = PropsWithChildren<{}>;

// CommandBar
const providers = [ApolloClientProvider, ThemeProvider];

const RootLayout: FC<Props> = ({ children }) => (
  <html lang="en" suppressHydrationWarning>
    <body className={inter.className}>
      <LoadingIndicator />
      {providers.reduceRight(
        (child, Provider) => (
          <Provider key={child?.toString()}>{child}</Provider>
        ),
        children,
      )}
      <Analytics />
    </body>
  </html>
);

export default RootLayout;
